server.port: 8080

logging:
  config: classpath:log4j2.yaml
  level.org.hibernate.type: trace

spring:
  datasource:
    url: >
      jdbc:mysql://localhost:3306/sample_db?
      useUnicode=true&
      characterEncoding=utf8&
      useSSL=false
    username: root
    password: password
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties.hibernate:
      show_sql: true
      use_sql_comments: true
      format_sql: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql